# 베이스 이미지
FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./requirements.txt /app
COPY ./mk_macro_pg.py /app
# 의존성 설치
RUN pip install --no-cache-dir -r requirements.txt


RUN mkdir -p /app/postgres
COPY ./postgres_hook.py /app/postgres
# 모델 및 산출물을 저장할 디렉토리 생성
RUN mkdir -p /app/model_materials

# 스크립트 실행 명령어 설정
ENTRYPOINT ["python", "./mk_macro_pg.py"]
