# 베이스 이미지
FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    docker.io \
    vim \
    procps \
    && rm -rf /var/lib/apt/lists/*

# 작업 디렉터리 설정
WORKDIR /app
COPY . .

# 필요한 패키지 설치
RUN pip install --no-cache-dir -r requirements.txt

# 포트
EXPOSE 5000

# Flask 애플리케이션 실행
ENTRYPOINT ["python3", "/app/app.py"]
